#!/usr/bin/env bash
set -efu

{ # this ensures the entire script is downloaded #

# METHODS #
	color() {
		echo -e "$1\e[39m\033[0;37m\e[0m"
	}
	
	error() {
		color "\n\e[91m\033[41m\e[K"
		color "\e[1;37m\033[41m\e[K  ERROR"
		color "\e[1;37m\033[41m\e[K  $1\e[K"
		color "\e[91m\033[41m\e[K \n"
	}
	
	detect_os() {
		os_arch=`uname -m`
		os_type=`uname -s`
		
		case $os_arch in
		i?86) os_arch="i386" ;;
			*) : ;;
		esac
		
		if [ "$os_type" = 'Linux' ]; then
			# Debian / Ubuntu
			if [ -e '/etc/debian_version' ]; then
			
				# Mostly ubuntu, but not debian
				if [ -e '/etc/lsb-release' ]; then
					. /etc/lsb-release
					os_name=$DISTRIB_ID
					os_version=$DISTRIB_RELEASE
					os_code=$DISTRIB_CODENAME
				else
					. /etc/os-release
					os_name='Debian'
					os_version=`head -1 /etc/debian_version`
					os_code=$VERSION_CODENAME
					
					if [ "$os_version" = 'trixie/sid' ]; then
						os_version=13.0
					fi
				fi
				
			# RedHat
			elif [ -e '/etc/redhat-release' ]; then
				os_name=`awk '{print $1}' /etc/redhat-release`
				os_version=`head -1 /etc/redhat-release | sed -e 's/[^0-9.]*\([0-9.]*\).*/\1/g' | awk -F'.' '{print $1}'`
				os_code="?"
					
				case $os_name$os_version$os_arch in
					CentOS*|Cloud*|Virtuozzo*|AlmaLinux*|Rocky*)
						;;
					Red*)
						os_name="RedHat";
						;;
					*)
						error "Unknown OS is specified in /etc/redhat-release!"
						;;
				esac
			fi
			
		else
			error "You've tried to install fruithost on \033[1;37m$os_type. 😒\nCurrently, fruithost can only installed on Linux-Systems, Sorry!"
		fi
	}


# CALL #
	color "\e[33mWelcome to fruithost installer!"
	
	if [ `id -u` -ne 0 ]; then
	  error "Please run the installation as root!                             "
	  exit
	fi
	
	color "\e[33mDetecting OS,..."
	detect_os
	
	color "    \e[1;35mType:\e[0;0m             $os_type"
	color "    \e[1;35mName:\e[0;0m             $os_name"
	color "    \e[1;35mVersion:\e[0;0m          $os_version"
	color "    \e[1;35mArchitecture:\e[0;0m     $os_arch"
	color "    \e[1;35mCodename:\e[0;0m         $os_code\n"
	
	url="https://update.fruithost.de/installer/$os_type/$os_name/$os_version/$os_arch"
	
	curl --connect-timeout 10 -IsL "$url" > /dev/null || ( error "Cannot connect to $url to download the fruithost-Installer.\n\nCheck your firewall settings. If you are using a proxy, make sure you have set the HTTPS_PROXY environment variable." && exit 132 )
	
	bash <(curl -H 'Cache-Control: no-cache, no-store' -L -s -o- $url || wget -q -O - $url)
	
} # this ensures the entire script is downloaded #